[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "oplanet"
version = "2.2.18"
description = "Lightweight Python wrapper around the NASA Exoplanet Archive."
readme = "README.md"
requires-python = ">=3.10"
license = { file = "LICENSE" }
authors = [
  { name = "ProfesseurShadoko" }
]
dependencies = [
  "oakley>=3.1.5",
  "numpy>=2.0.0",
  "pandas>=2.2.2",
  "astroquery>=0.4.7",
  "astropy>=5.0",
  "scipy>=1.13.0",
  "matplotlib>=3.5.0",
  "requests>=2.19.0",
  "beautifulsoup4>=4.8.0",
  "huggingface_hub>=0.20.0",
  "Jinja2"
]
keywords = ["astronomy", "exoplanets", "nasa", "astrophysics"]
classifiers = [
  "Development Status :: 3 - Alpha",
  "Intended Audience :: Science/Research",
  "License :: OSI Approved :: MIT License",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3 :: Only",
  "Topic :: Scientific/Engineering :: Astronomy",
]

[project.urls]
Homepage = "https://github.com/ProfesseurShadoko/oplanet"
Repository = "https://github.com/ProfesseurShadoko/oplanet"
Issues = "https://github.com/ProfesseurShadoko/oplanet/issues"

[tool.setuptools]
include-package-data = false

[tool.setuptools.packages.find]
include = ["oplanet*"]


